sonar.projectKey=taller-app-reservas
sonar.projectName=Taller App Reservas
sonar.projectVersion=1.0

sonar.sources=\
  auth-service/src,\
  booking-service/src,\
  user-service,\
  notification-service,\
  frontend/src,\
  orders-service/src

sonar.tests=\
  auth-service/src,\
  booking-service/src,\
  orders-service/src

sonar.test.inclusions=**/*.test.js,**/*.spec.js

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/.next/**,\
  **/coverage/**,\
  **/*.config.js,\
  **/*.config.mjs

sonar.javascript.lcov.reportPaths=\
  auth-service/coverage/lcov.info,\
  booking-service/coverage/lcov.info,\
  orders-service/coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
